### PR TITLE
Optimize license server - CodeMeter runtime is automatically installed

### PR DESCRIPTION
**Pull request by RenjithPNair**
- Licenses server uses the latest AMAZON Linux 2023 version
- CodeMeter User Runtime for Linux (Driver Only) version is automatically installed through user data
    Default version used : 8.10 | Driver Only | 2024-04-24 | multi language | Linux 64 bit RPM package 
- After installation, the license server is configured as network license server

### CODE REVIEW

**Review by mariogluhakovic — COMMENTED** [review]
What happens if this terraform is run in AWS account with already existing License server?

**Comment by RenjithPNair** [comment]
> What happens if this terraform is run in AWS account with already existing License server?

By default, user data scripts runs when you first launch an instance. So in this case user data script is updated but nothing runs.

But i saw in documentation that there is some option to ensure that user data runs every time you restart your instance.

**Comment by lukabudak** [comment]
> > What happens if this terraform is run in AWS account with already existing License server?
> 
> Update the user data script and restart the license server. But user data script wont run because by default, it run only during the boot cycle when you first launch an instance.
> 
> ami change is ignored in the lifecycle

It appears that the changes proposed by this Pull request might break an already deployed licence server since it removes already initialised CmContainer on the restart.

**Review by mariogluhakovic — APPROVED** [review]
LGTM

**Pull request merged**
